### ISSUE TITLE
Hyperparameter for reproducing the results in table 1

### ISSUE THREAD

**Issue by niclaspopp** [andyz245/RobustKD#1]
Dear authors, 

We would like to replicate the main results from table 1 in your paper (more precisely the ResNet and ViT baselines as well as the DAT/DAD results) using this codebase. However, using the script provided as https://github.com/lapisrocks/DiscreteAdversarialDistillation/blob/main/easyrobust/scripts/vit.sh yields to substantially worse performance. Thus, we would be thankful if you could provide the exact training scripts and/or hyperparameters. If possible, it would be great if you could also share the adversarial example images used in DAD. 

Thank you very much in advance!

**Comment by andyz245** [comment]
Thanks for reaching out. Responded over email but commenting here in case others run into similar issues.

To reproduce our results, either set the number of epochs to 300 with a randomly initialized ViT, or start from the pretrained base model we provided and fine tune for 30 epochs.
